/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/airports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Airports */
        get: operations["get_airports_api_v1_airports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedules/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Schedule Status */
        get: operations["get_schedule_status_api_v1_schedules_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Search */
        post: operations["post_search_api_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AirportItem */
        AirportItem: {
            /** City */
            city: string;
            /** Code */
            code: string;
            /** Country Code */
            country_code: string;
            /** Name */
            name: string;
            /** State Or Region */
            state_or_region: string | null;
            /** Timezone */
            timezone: string;
        };
        /** AirportRef */
        AirportRef: {
            /** City */
            city: string;
            /** Code */
            code: string;
            /** Country Code */
            country_code: string;
        };
        /** AirportSearchResponse */
        AirportSearchResponse: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["AirportItem"][];
        };
        /** ApiError */
        ApiError: {
            code: components["schemas"]["ApiErrorCode"];
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
        };
        /**
         * ApiErrorCode
         * @description Stable public error codes (PHASE.md §Public API Error Contract).
         * @enum {string}
         */
        ApiErrorCode: "INVALID_REQUEST" | "INVALID_AIRPORT" | "INVALID_DEPARTURE_DATE" | "DATE_OUTSIDE_SCHEDULE_RANGE" | "NO_ACTIVE_SCHEDULE" | "INVALID_CONNECTION_RANGE" | "INVALID_TIME_FILTER" | "INVALID_PRICE_FILTER" | "UNSUPPORTED_SORT" | "DATABASE_UNAVAILABLE" | "INTERNAL_ERROR";
        /**
         * ApiErrorResponse
         * @description The single error envelope for all non-2xx API responses.
         */
        ApiErrorResponse: {
            error: components["schemas"]["ApiError"];
        };
        /** ApiWarning */
        ApiWarning: {
            code: components["schemas"]["WarningCode"];
            /** Message */
            message: string;
        };
        /** AvailabilityModel */
        AvailabilityModel: {
            /** Checked At */
            checked_at?: string | null;
            /**
             * Confidence
             * @default LOW
             */
            confidence: string;
            /** Source */
            source?: string | null;
            status: components["schemas"]["AvailabilityStatus"];
        };
        /**
         * AvailabilityStatus
         * @enum {string}
         */
        AvailabilityStatus: "NOT_CHECKED" | "AVAILABLE" | "UNAVAILABLE" | "UNKNOWN" | "STALE";
        /** DataFreshness */
        DataFreshness: {
            /** Availability Checked At */
            availability_checked_at?: string | null;
            /** Schedule Effective End */
            schedule_effective_end: string | null;
            /** Schedule Effective Start */
            schedule_effective_start: string | null;
            /** Schedule Source */
            schedule_source: string | null;
            /** Schedule Updated At */
            schedule_updated_at: string | null;
            /** Schedule Version */
            schedule_version: string | null;
        };
        /** ItineraryModel */
        ItineraryModel: {
            /** Airborne Duration Minutes */
            airborne_duration_minutes: number;
            /**
             * Arrival At
             * Format: date-time
             */
            arrival_at: string;
            availability: components["schemas"]["AvailabilityModel"];
            /** Booking Url */
            booking_url?: string | null;
            /** Connection Count */
            connection_count: number;
            /**
             * Departure At
             * Format: date-time
             */
            departure_at: string;
            destination: components["schemas"]["AirportRef"];
            /** Itinerary Id */
            itinerary_id: string;
            origin: components["schemas"]["AirportRef"];
            price: components["schemas"]["PriceModel"];
            /** Segments */
            segments: components["schemas"]["SegmentModel"][];
            /** Total Duration Minutes */
            total_duration_minutes: number;
            /** Total Layover Minutes */
            total_layover_minutes: number;
        };
        /** OriginRef */
        OriginRef: {
            /** City */
            city: string;
            /** Code */
            code: string;
            /** Timezone */
            timezone: string;
        };
        /** PriceModel */
        PriceModel: {
            /** Amount */
            amount: string | null;
            /** Currency */
            currency: string;
            /** Disclaimer */
            disclaimer: string;
            /** Segment Count */
            segment_count: number;
            status: components["schemas"]["PriceStatus"];
            /** Verified At */
            verified_at?: string | null;
        };
        /**
         * PriceStatus
         * @enum {string}
         */
        PriceStatus: "ESTIMATED" | "VERIFIED" | "STALE" | "UNAVAILABLE" | "UNKNOWN";
        /** ScheduleStatusResponse */
        ScheduleStatusResponse: {
            /** Active */
            active: boolean;
            /** Effective End */
            effective_end?: string | null;
            /** Effective Start */
            effective_start?: string | null;
            /** Retrieved At */
            retrieved_at?: string | null;
            /**
             * Route Count
             * @default 0
             */
            route_count: number;
            /**
             * Scheduled Flight Count
             * @default 0
             */
            scheduled_flight_count: number;
            /** Source */
            source?: string | null;
            /** Version */
            version?: string | null;
        };
        /** SearchRequest */
        SearchRequest: {
            /** Arrive Before */
            arrive_before?: string | null;
            /** Depart After */
            depart_after?: string | null;
            /** Depart Before */
            depart_before?: string | null;
            /**
             * Departure Date
             * Format: date
             */
            departure_date: string;
            /**
             * Domestic Only
             * @default false
             */
            domestic_only: boolean;
            /**
             * International Only
             * @default false
             */
            international_only: boolean;
            /**
             * Max Connection Minutes
             * @default 240
             */
            max_connection_minutes: number;
            /**
             * Max Connections
             * @default 1
             */
            max_connections: number;
            /** Max Price */
            max_price?: number | null;
            /**
             * Max Total Duration Minutes
             * @default 720
             */
            max_total_duration_minutes: number | null;
            /**
             * Min Connection Minutes
             * @default 45
             */
            min_connection_minutes: number;
            /** Origin */
            origin: string;
            /** @default PRICE */
            sort: components["schemas"]["SortMode"];
        };
        /** SearchResponse */
        SearchResponse: {
            data_freshness: components["schemas"]["DataFreshness"];
            /**
             * Departure Date
             * Format: date
             */
            departure_date: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            origin: components["schemas"]["OriginRef"];
            /** Result Count */
            result_count: number;
            /** Results */
            results: components["schemas"]["ItineraryModel"][];
            /** Search Id */
            search_id: string;
            /** Warnings */
            warnings: components["schemas"]["ApiWarning"][];
        };
        /** SegmentModel */
        SegmentModel: {
            /**
             * Arrival At
             * Format: date-time
             */
            arrival_at: string;
            /** Carrier */
            carrier: string;
            /**
             * Departure At
             * Format: date-time
             */
            departure_at: string;
            /** Destination */
            destination: string;
            /** Duration Minutes */
            duration_minutes: number;
            /** Flight Number */
            flight_number: string;
            /** Origin */
            origin: string;
            /** Sequence */
            sequence: number;
        };
        /**
         * SortMode
         * @description Deterministic sort modes (PHASE.md §14). Each defines stable tie-breakers.
         * @enum {string}
         */
        SortMode: "PRICE" | "TOTAL_DURATION" | "EARLIEST_DEPARTURE" | "LATEST_DEPARTURE" | "DESTINATION";
        /**
         * WarningCode
         * @description Stable public warning codes attached to successful responses.
         * @enum {string}
         */
        WarningCode: "AVAILABILITY_NOT_CHECKED" | "NO_MATCHING_ITINERARIES" | "RESULTS_TRUNCATED";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_airports_api_v1_airports_get: {
        parameters: {
            query: {
                /** @description Non-whitespace airport code, city, or name. */
                query: string;
                /** @description Maximum results (bounded). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirportSearchResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description No active schedule */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_schedule_status_api_v1_schedules_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleStatusResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description No active schedule */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    post_search_api_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description No active schedule */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
}
